### ISSUE TITLE
Elements tagged with EPartService.REMOVE_ON_HIDE_TAG are not removed

### ISSUE THREAD

**Issue by martinbluehweis** [eclipse/efxclipse-rt#12]

**Comment by tomsontom** [comment]
Ok I see what's going on! 

We are leaking the rendering-context for NOT-YET-RENDER MPartStack children - the reason is that a MPartStack creates its children-widgets lazy but to make the TabItem connected to the model we are creating IEclipseContexts before hand (see BaseStackRenderer#createStackItem).

The clean up of the context is done when BaseRenderer#destroyWidget is called who is called by PartRenderingEngine#removeGUI now the problem is that because we have not yet rendered this StackItem we don't have assigned a renderer we skip that step.

Same problem is in all areas where we have lazy-object creation in place (IIRC PerspectiveStack)
